In [2]:
model.parameters()

[[[ 0.9993694   0.5485256   0.3619677  -0.07908762]
  [ 0.1888548   0.5695789   0.8287675  -0.7252917 ]
  [-0.4862165   0.1122268   0.5645595  -0.342375  ]]
 [syft.FloatTensor:1 grad:None size:3x4 c:[] p:[] init:], [[ 0.  0.  0.  0.]]
 [syft.FloatTensor:2 grad:None size:1x4 c:[] p:[] init:], [[ 0.9993694   0.5485256 ]
  [ 0.3619677  -0.07908762]
  [ 0.1888548   0.5695789 ]
  [ 0.8287675  -0.7252917 ]]
 [syft.FloatTensor:3 grad:None size:4x2 c:[] p:[] init:], [[ 0.  0.]]
 [syft.FloatTensor:4 grad:None size:1x2 c:[] p:[] init:]]

In [53]:
import syft
import syft.nn as nn
import syft.optim as optim
from syft.controller import models, tensors
import imp
imp.reload(syft)
imp.reload(syft.nn)

import numpy as np
from syft import FloatTensor

model = nn.Sequential([
    nn.Linear(3,4),
    nn.ReLU(),
    nn.Linear(4,2),
    nn.Softmax(1),
    nn.Log()
])

model.summary()

# optimizer = optim.SGD(model.parameters(), lr=0.1, momentum=0.9)

# optimizer = optim.SGD(model.parameters(), 
#                       lr=0.1, 
#                       momentum=0.9,
#                       decay=0.001)
optimizer = optim.RMSProp(model.parameters(), lr=0.01, rho=0.99, epsilon=0.000000001)
criterion = syft.nn.NLLLoss()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
linear_8 (Linear)            (None, 4)                 16
_________________________________________________________________
relu_9 (ReLU)                (dynamic)                 0
_________________________________________________________________
linear_10 (Linear)           (None, 2)                 10
_________________________________________________________________
softmax_11 (Softmax)         (dynamic)                 0
_________________________________________________________________
log_12 (Log)                 (dynamic)                 0
Total params: 26
Trainable params: 26
Non-trainable params: 0
_________________________________________________________________



In [54]:
input = FloatTensor([[0,0,1],[0,1.0,1],[1,0,1],[1,1,1]]*2000,autograd=True)
target = FloatTensor([[0,0],[0,0],[0,1],[0,1]]*2000,autograd=True)

In [55]:
final_loss = model.fit(input=input,
                       target=target,                       
                       batch_size=100,
                       criterion=criterion,
                       optim=optimizer,
                       iters=10,log_interval=4)
final_loss

Number of Batches:80


HBox(children=(IntProgress(value=0, max=9), HTML(value='')))

HBox(children=(IntProgress(value=0, max=80), HTML(value='')))

HBox(children=(IntProgress(value=0, max=80), HTML(value='')))

HBox(children=(IntProgress(value=0, max=80), HTML(value='')))

HBox(children=(IntProgress(value=0, max=80), HTML(value='')))

HBox(children=(IntProgress(value=0, max=80), HTML(value='')))

HBox(children=(IntProgress(value=0, max=80), HTML(value='')))

HBox(children=(IntProgress(value=0, max=80), HTML(value='')))

HBox(children=(IntProgress(value=0, max=80), HTML(value='')))

HBox(children=(IntProgress(value=0, max=80), HTML(value='')))

HBox(children=(IntProgress(value=0, max=80), HTML(value='')))

'103.9721'

In [4]:
input

[[ 0.  0.  1.]
 [ 0.  1.  1.]
 [ 1.  0.  1.]
 ..., 
 [ 0.  1.  1.]
 [ 1.  0.  1.]
 [ 1.  1.  1.]]
[syft.FloatTensor:5 grad:None size:8000x3 c:[] p:[] init:]